name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # paths:
    #   - 'docs/**'

permissions:
  actions: write
  checks: write
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: npm install
        run: npm ci

      - name: Install dependencies and build
        run: |
          npm run build
        env:
          GITHUB_PAGES: true

      - name: Push to GitHub
        uses: EndBug/add-and-commit@main
        with:
          # ブランチ名はデフォルトブランチ名にする(main or master)
          branch: main
          message: ":rocket: Update"
  